# Generated by Django 6.0.2 on 2026-02-21 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(choices=[('uiux', 'UI/UX Design Project'), ('django', 'Django Project'), ('fullstack', 'FullStack Project'), ('freelance', 'Freelance Collaboration'), ('internship', 'Internship'), ('hi', 'Just saying hi')], max_length=20)),
                ('budget', models.CharField(choices=[('<10', '< $10'), ('10-20', '$10 – $20'), ('20-30', '$20 – $30'), ('30+', '$30+'), ('not_sure', 'Not sure')], max_length=20)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
            ],
        ),
    ]
